name: rimbakawal
version: 0.4.3+9
publish_to: 'none'

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.8.1
  connectivity_plus: ^7.3.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.14.0
  firebase_messaging: ^16.6.0
  flutter_map: ^8.3.2
  flutter_secure_storage: ^10.3.1
  geolocator: ^14.0.3
  hive_ce_flutter: ^2.3.4
  http: ^1.5.0
  image_picker: ^1.2.3
  latlong2: ^0.10.1
  nfc_manager: ^4.2.1
  pdf: ^3.12.0
  printing: ^5.14.3
  url_launcher: ^6.3.2
  wakelock_plus: ^1.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/patrol_alarm.wav
