name: rimbakawal
version: 0.2.0+1
publish_to: 'none'

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.8.1
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  geolocator: ^14.0.2
  image_picker: ^1.2.3
  nfc_manager: ^4.2.1
  pdf: ^3.12.0
  printing: ^5.14.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/patrol_alarm.wav
