from pathlib import Path

p = Path('lib/features/admin/user_maintenance_screen.dart')
text = p.read_text(encoding='utf-8')

def rep(old, new):
    global text
    if new in text:
        return
    if old not in text:
        raise RuntimeError(f'anchor missing: {old[:110]!r}')
    text = text.replace(old, new, 1)

rep("  int? _departmentId;\n  String? _newProfilePicture;\n", "  int? _departmentId;\n  int? _companyId;\n  String? _newProfilePicture;\n")
rep("    _departmentId = widget.user.departmentId;\n  }\n", "    _departmentId = widget.user.departmentId;\n    _companyId = widget.user.companyId;\n  }\n")
rep("    if (nama.length < 3 || _departmentId == null) {\n      setState(() => _error = 'Lengkapkan nama dan Sekolah pengguna.');\n      return;\n    }\n", "    final isAdministration = _jawatan == 'Administration';\n    if (nama.length < 3 || (isAdministration ? _companyId == null : _departmentId == null)) {\n      setState(() => _error = isAdministration\n          ? 'Lengkapkan nama dan Syarikat pengguna.'\n          : 'Lengkapkan nama dan Sekolah pengguna.');\n      return;\n    }\n")
rep("        jawatan: _jawatan,\n        departmentId: _departmentId!,\n        noPk: _noPkController.text.trim(),\n", "        jawatan: _jawatan,\n        departmentId: isAdministration ? null : _departmentId,\n        companyId: isAdministration ? _companyId : null,\n        noPk: isAdministration ? '' : _noPkController.text.trim(),\n")
rep("    final active = widget.departments.where((item) => item.active).toList();\n    final preview = _previewImage();\n", "    final active = widget.departments.where((item) => item.active).toList();\n    final activeCompanies = widget.companies.where((item) => item.active || item.id == _companyId).toList();\n    final isAdministration = _jawatan == 'Administration';\n    final preview = _previewImage();\n")
rep("                        if (value != null) setState(() => _jawatan = value);\n", "                        if (value != null) {\n                          setState(() {\n                            _jawatan = value;\n                            if (value == 'Administration' && _companyId == null && activeCompanies.isNotEmpty) {\n                              _companyId = activeCompanies.first.id;\n                            }\n                            if (value != 'Administration' && _departmentId == null && active.isNotEmpty) {\n                              _departmentId = active.first.id;\n                            }\n                          });\n                        }\n")
rep('''              DropdownButtonFormField<int>(\n                initialValue: _departmentId,\n                decoration: const InputDecoration(\n                  labelText: 'Sekolah',\n                  prefixIcon: Icon(Icons.account_tree_outlined),\n                ),\n                items: active\n                    .map(\n                      (department) => DropdownMenuItem<int>(\n                        value: department.id,\n                        child: Text(department.name),\n                      ),\n                    )\n                    .toList(),\n                onChanged: _saving\n                    ? null\n                    : (value) => setState(() => _departmentId = value),\n              ),\n''', '''              if (isAdministration)\n                DropdownButtonFormField<int>(\n                  initialValue: activeCompanies.any((item) => item.id == _companyId) ? _companyId : null,\n                  decoration: const InputDecoration(\n                    labelText: 'Syarikat',\n                    prefixIcon: Icon(Icons.business_rounded),\n                    helperText: 'Akaun ini mengakses laporan semua Sekolah di bawah syarikat.',\n                  ),\n                  items: activeCompanies\n                      .map((company) => DropdownMenuItem<int>(value: company.id, child: Text(company.name)))\n                      .toList(),\n                  onChanged: _saving ? null : (value) => setState(() => _companyId = value),\n                )\n              else\n                DropdownButtonFormField<int>(\n                  initialValue: _departmentId,\n                  decoration: const InputDecoration(\n                    labelText: 'Sekolah',\n                    prefixIcon: Icon(Icons.account_tree_outlined),\n                  ),\n                  items: active\n                      .map((department) => DropdownMenuItem<int>(value: department.id, child: Text(department.name)))\n                      .toList(),\n                  onChanged: _saving ? null : (value) => setState(() => _departmentId = value),\n                ),\n''')
p.write_text(text, encoding='utf-8')
