from pathlib import Path

p = Path('lib/features/admin/user_maintenance_screen.dart')
text = p.read_text(encoding='utf-8')

def rep(old, new):
    global text
    if new in text:
        return
    if old not in text:
        raise RuntimeError(f'anchor missing: {old[:110]!r}')
    text = text.replace(old, new, 1)

# This occurrence is in _AddUserDialog after the edit-dialog state was already patched.
rep("  int? _departmentId;\n  bool _saving = false;\n", "  int? _departmentId;\n  int? _companyId;\n  bool _saving = false;\n")
rep("    if (active.isNotEmpty) _departmentId = active.first.id;\n  }\n", "    if (active.isNotEmpty) _departmentId = active.first.id;\n    final companies = widget.companies.where((item) => item.active).toList();\n    if (companies.isNotEmpty) _companyId = companies.first.id;\n  }\n")
rep("    if (name.length < 3 || ic.length != 12 || _departmentId == null) {\n      setState(\n        () => _error =\n            'Lengkapkan nama, No. Kad Pengenalan 12 digit dan Sekolah.',\n      );\n      return;\n    }\n", "    final isAdministration = _jawatan == 'Administration';\n    if (name.length < 3 || ic.length != 12 || (isAdministration ? _companyId == null : _departmentId == null)) {\n      setState(\n        () => _error = isAdministration\n            ? 'Lengkapkan nama, No. Kad Pengenalan 12 digit dan Syarikat.'\n            : 'Lengkapkan nama, No. Kad Pengenalan 12 digit dan Sekolah.',\n      );\n      return;\n    }\n")
rep("        jawatan: _jawatan,\n        departmentId: _departmentId!,\n        noPk: _noPkController.text.trim(),\n", "        jawatan: _jawatan,\n        departmentId: isAdministration ? null : _departmentId,\n        companyId: isAdministration ? _companyId : null,\n        noPk: isAdministration ? '' : _noPkController.text.trim(),\n")
rep("    final active = widget.departments.where((item) => item.active).toList();\n    return AlertDialog(\n", "    final active = widget.departments.where((item) => item.active).toList();\n    final activeCompanies = widget.companies.where((item) => item.active).toList();\n    final isAdministration = _jawatan == 'Administration';\n    return AlertDialog(\n")
rep("                onChanged: (value) {\n                  if (value != null) setState(() => _jawatan = value);\n                },\n", "                onChanged: (value) {\n                  if (value != null) {\n                    setState(() {\n                      _jawatan = value;\n                      if (value == 'Administration' && _companyId == null && activeCompanies.isNotEmpty) {\n                        _companyId = activeCompanies.first.id;\n                      }\n                      if (value != 'Administration' && _departmentId == null && active.isNotEmpty) {\n                        _departmentId = active.first.id;\n                      }\n                    });\n                  }\n                },\n")
rep('''              DropdownButtonFormField<int>(\n                initialValue: _departmentId,\n                decoration: const InputDecoration(\n                  labelText: 'Sekolah',\n                  prefixIcon: Icon(Icons.account_tree_outlined),\n                ),\n                items: active\n                    .map(\n                      (department) => DropdownMenuItem<int>(\n                        value: department.id,\n                        child: Text(department.name),\n                      ),\n                    )\n                    .toList(),\n                onChanged: (value) => setState(() => _departmentId = value),\n              ),\n''', '''              if (isAdministration)\n                DropdownButtonFormField<int>(\n                  initialValue: activeCompanies.any((item) => item.id == _companyId) ? _companyId : null,\n                  decoration: const InputDecoration(\n                    labelText: 'Syarikat',\n                    prefixIcon: Icon(Icons.business_rounded),\n                    helperText: 'Pentadbiran Syarikat dipaut terus kepada Syarikat, bukan satu Sekolah.',\n                  ),\n                  items: activeCompanies\n                      .map((company) => DropdownMenuItem<int>(value: company.id, child: Text(company.name)))\n                      .toList(),\n                  onChanged: (value) => setState(() => _companyId = value),\n                )\n              else\n                DropdownButtonFormField<int>(\n                  initialValue: _departmentId,\n                  decoration: const InputDecoration(\n                    labelText: 'Sekolah',\n                    prefixIcon: Icon(Icons.account_tree_outlined),\n                  ),\n                  items: active\n                      .map((department) => DropdownMenuItem<int>(value: department.id, child: Text(department.name)))\n                      .toList(),\n                  onChanged: (value) => setState(() => _departmentId = value),\n                ),\n''')
p.write_text(text, encoding='utf-8')
